# Script to run T-fRL and T-cafRL models 

# Prepare Environment
```{r}
# Load packages
pacman::p_load(tidyverse, 
               ggplot2, 
               tictoc, 
               bayesplot, 
               cmdstanr)

# Load functions
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
source("../../1-simulation/talwar/simulation_functions_talwar.R")
source("../../utils/quality_check_functions.R")
```

####### FRL #######

# Simulate data
```{r}
# Parameters
params = list(
  model = "fRL",
  group = "test",
  n_correct = 6,
  alpha = 0.05, 
  beta = 1,
  theta_init = NA,
  epsilon = NA)

# Run simulation
d = run_simulation(params, 1, 1)

# Prepare data for model
data <- list(n_trials = nrow(d),
             stage = d$stage,
             trial = d$trial,
             choice = d$choice,
             stimulus = d$stimulus,
             alpha_mean = 0,
             alpha_sd = 1.5,
             beta_alpha = 2,
             beta_beta = 0.5)
```

# Run model in rstan
```{r}
# RUN MODEL --------------------
# Define file
file = file.path("1_fRL/fRL_loglik.stan")
stan_file = rstan::stan_model(file = file, auto_write = T)
  
# Fit model
fit <- rstan::sampling(stan_file, data = data,
                       seed = 145, refresh = 0,
                       iter = 3000, warmup = 1000, 
                       chains = 4, cores = 4, 
                       control = list(adapt_delta = 0.99, max_treedepth = 20))


# DIAGNOSTICS --------------------
# Get draws and relevant parameters
draws_df <- as.data.frame(fit)
relevant_pars = (colnames(draws_df))[1:8]

# Diagnose
rstan::check_hmc_diagnostics(fit)

# Summary
rstan::summary(fit, relevant_pars)$summary

# Chains
rstan::traceplot(fit, relevant_pars)

# Prior predictive checks
pp_predictive_hist("prior_pred", fit, d)
pp_predictive_dens("prior_pred", fit, d, 100)

# Posterior predictive checks
pp_predictive_hist("posterior_pred", fit, d)
pp_predictive_dens("posterior_pred", fit, d, 100)

# Prior posterior update in log
plot_prior_posterior(draws_df, "alpha_prior_log", "alpha_posterior_log", "Alpha Log")

# Prior posterior update in p
plot_prior_posterior(draws_df, "alpha_prior_p", "alpha_posterior_p", "Alpha P")

# Prior posterior update for beta
plot_prior_posterior(draws_df, "beta_prior", "beta_posterior", "Beta")

```

####### CA-FRL ALL FREE PARAMETRES #######

# Simulate data
```{r}
# Parameters
params = list(
  model = "cafRL",
  group = "test",
  n_correct = 6,
  alpha = 0.1, 
  beta = 1,
  theta_init = logit_scaled(0.1),
  epsilon = NA)

# Run simulation
d = run_simulation(params, 1, sim_seeds = 1)

# Prepare data for model
data <- list(n_trials = nrow(d),
             stage = d$stage,
             trial = d$trial,
             choice = d$choice,
             stimulus = d$stimulus,
             alpha_mean = 0,
             alpha_sd = 1.5,
             beta_alpha = 2,
             beta_beta = 0.5,
             theta0_mean = 0,
             theta0_sd = 1.5)
```

# Run model in rstan
```{r}
# RUN MODEL --------------------
# Define file
file = file.path("2_cafRL/cafRL_loglik.stan")
stan_file = rstan::stan_model(file = file, auto_write = T)
  
# Fit model
fit <- rstan::sampling(stan_file, data = data,
                       seed = 145, refresh = 0,
                       iter = 3000, warmup = 1000, 
                       chains = 4, cores = 4, 
                       control = list(adapt_delta = 0.99, max_treedepth = 20))


# DIAGNOSTICS --------------------
# Get draws and relevant parameters
draws_df <- as.data.frame(fit)
relevant_pars = (colnames(draws_df))[1:13]
colnames(draws_df)

# Diagnose
rstan::check_hmc_diagnostics(fit)

# Summary
rstan::summary(fit, relevant_pars)$summary

# Chains
rstan::traceplot(fit, relevant_pars)

# Prior predictive checks
pp_predictive_hist("prior_pred", fit, d)
pp_predictive_dens("prior_pred", fit, d, 500)

# Posterior predictive checks
pp_predictive_hist("posterior_pred", fit, d)
pp_predictive_dens("posterior_pred", fit, d, 500)

# Prior posterior update in log
plot_prior_posterior(draws_df, "alpha_prior_log", "alpha_posterior_log", "Alpha Log")

# Prior posterior update in p
plot_prior_posterior(draws_df, "alpha_prior_p", "alpha_posterior_p", "Alpha P")

# Prior posterior update for beta
plot_prior_posterior(draws_df, "beta_prior", "beta_posterior", "Beta")

# Prior posterior update for theta0 in log
plot_prior_posterior(draws_df, "theta0_prior_log", "theta0_posterior_log", "Theta0 Log")

# Prior posterior update for theta0 in p
plot_prior_posterior(draws_df, "theta0_prior_p", "theta0_posterior_p", "Theta0 P")

```


####### CA-FRL BETA FIXED #######

# Simulate data
```{r}
# Parameters
params = list(
  model = "cafRL",
  group = "fixed beta",
  n_correct = 6,
  alpha = 0.7, 
  beta = 1,
  theta_init = -2.5,
  epsilon = NA)

# Run simulation
d = run_simulation(params, 1, 1)

# Prepare data for model
data <- list(n_trials = nrow(d),
             stage = d$stage,
             trial = d$trial,
             choice = d$choice,
             stimulus = d$stimulus,
             alpha_mean = 0,
             alpha_sd = 1.5,
             theta0_mean = 0,
             theta0_sd = 1.5,
             beta = 2)
```

# Run model in rstan
```{r}
# RUN MODEL --------------------
# Define file
file = file.path("2_cafRL/cafRL_alpha_theta0_loglik.stan")
stan_file = rstan::stan_model(file = file, auto_write = T)
  
# Fit model
fit <- rstan::sampling(stan_file, data = data,
                       seed = 145, refresh = 0,
                       iter = 3000, warmup = 1000, 
                       chains = 4, cores = 4, 
                       control = list(adapt_delta = 0.99, max_treedepth = 20))


# DIAGNOSTICS --------------------
# Get draws and relevant parameters
draws_df <- as.data.frame(fit)
relevant_pars = (colnames(draws_df))[1:10]

# Diagnose
rstan::check_hmc_diagnostics(fit)

# Summary
rstan::summary(fit, relevant_pars)$summary

# Chains
rstan::traceplot(fit, relevant_pars)

# Prior predictive checks
pp_predictive_hist("prior_pred", fit, d)
pp_predictive_dens("prior_pred", fit, d, 100)

# Posterior predictive checks
pp_predictive_hist("posterior_pred", fit, d)
pp_predictive_dens("posterior_pred", fit, d, 100)

# Prior posterior update in log
plot_prior_posterior(draws_df, "alpha_prior_log", "alpha_posterior_log", "Alpha Log")
plot_prior_posterior(draws_df, "theta0_prior_log", "theta0_posterior_log", "Theta0 Log")

# Prior posterior update in p
plot_prior_posterior(draws_df, "alpha_prior_p", "alpha_posterior_p", "Alpha P")
plot_prior_posterior(draws_df, "theta0_prior_log", "theta0_posterior_log", "Theta0 Log")

```