# Script to run the Y-RL model

# Prepare Environment
```{r}
# Load packages
pacman::p_load(tidyverse, 
               ggplot2, 
               tictoc, 
               bayesplot, 
               #cmdstanr, 
               loox)

# Load functions
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
source("../../1-simulation/yearsley/simulation_functions_yearsley.R")
source("../../utils/quality_check_functions.R")
```

# Simulate data
```{r}

# Define Parameters 
params = list(
  group = "control",
  n_correct = 6,
  f = 0.1,
  r = 0.6,
  p = 0.7,
  d = 3,
  lambda = 0.05,
  switch1 = 0.95,
  switch2 = 0.95
)

# Run simulation
d = run_simulation(params, 1, 1)

# Prepare data for the model
data <- list(n_trials = nrow(d),
             stage = d$stage,
             trial = d$trial,
             choice = d$choice,
             stimulus = d$stimulus,
             alpha_pos_mean = 0,
             alpha_pos_sd = 1.5,
             alpha_neg_mean = 0,
             alpha_neg_sd = 1.5,
             f_mean = 0,
             f_sd = 1.5)

```

# Run model in rstan
```{r}
# RUN MODEL --------------------

# Define file
file = file.path("../../2-models/yearsley/yearsley_loglik.stan")
stan_file = rstan::stan_model(file = file, auto_write = T)
  
# Fit model with model parameters
fit <- rstan::sampling(stan_file, data = data,
                       seed = 145, refresh = 0,
                       iter = 3000, warmup = 1000, 
                       chains = 4, cores = 4, 
                       control = list(adapt_delta = 0.99, max_treedepth = 20))

# Run loo if desired
loo1 = loo::loo(fit)
loo2 = loo::loo(fit, moment_match=T, cores=4)


# DIAGNOSTICS --------------------
# Get draws from the fit and relevant parameters
draws_df <- as.data.frame(fit)
relevant_pars = (colnames(draws_df))[1:15]

# Diagnose
rstan::check_hmc_diagnostics(fit)

# Summary
rstan::summary(fit, relevant_pars)$summary

# Chains
rstan::traceplot(fit, relevant_pars)

# Prior predictive checks
pp_predictive_hist("prior_pred", fit, d)
pp_predictive_dens("prior_pred", fit, d, 100)

# Posterior predictive checks
pp_predictive_hist("posterior_pred", fit, d)
pp_predictive_dens("posterior_pred", fit, d, 100)

# Prior posterior update in log
plot_prior_posterior(draws_df, "alpha_pos_prior_log", "alpha_pos_posterior_log", "Alpha Pos Log")
plot_prior_posterior(draws_df, "alpha_neg_prior_log", "alpha_neg_posterior_log", "Alpha Neg Log")
plot_prior_posterior(draws_df, "f_prior_log", "f_posterior_log", "f Log")

# Prior posterior update in p
plot_prior_posterior(draws_df, "alpha_pos_prior_p", "alpha_pos_posterior_p", "Alpha Pos P")
plot_prior_posterior(draws_df, "alpha_neg_prior_p", "alpha_neg_posterior_p", "Alpha Neg P")
plot_prior_posterior(draws_df, "f_prior_p", "f_posterior_p", "f Prior/Posterior P")

```